version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: hackaton_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

volumes:
  pgdata:
