spring:
  application:
    name: CRM
  datasource:
    url: jdbc:postgresql://localhost:5435/crm_db
    username: user
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
crm:
  exchange: crm.exchange
  routing:
    order-created: order.created